<a href="https://colab.research.google.com/github/simran200719/crypto/blob/main/cryptocode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder,OneHotEncoder

In [2]:
crypto=pd.read_csv('https://raw.githubusercontent.com/simran200719/crypto/refs/heads/main/bitcoin-sv.csv')
crypto

Date    Open    High     Low   Close       Volume    Market Cap
0    2020-12-12  161.62  166.40  161.29  165.09  328095197.0  3.070047e+09
1    2020-12-11  166.44  166.69  159.65  161.65  396994620.0  3.005926e+09
2    2020-12-10  170.34  170.96  164.39  166.41  397472839.0  3.094229e+09
3    2020-12-09  173.35  173.47  161.74  170.32  532350698.0  3.166821e+09
4    2020-12-08  179.71  181.30  170.21  173.37  569515279.0  3.223309e+09
..          ...     ...     ...     ...     ...          ...           ...
760  2018-11-13  109.90  208.40  109.30  208.40   20708000.0  0.000000e+00
761  2018-11-12  116.46  123.56  104.45  112.06   10779600.0  0.000000e+00
762  2018-11-11   87.70  125.11   83.15  113.47    8902820.0  0.000000e+00
763  2018-11-10   70.27   98.51   61.19   87.06    4748070.0  0.000000e+00
764  2018-11-09   88.30   89.57   50.68   68.75    2585660.0  0.000000e+00

[765 rows x 7 columns]

In [3]:
crypto.drop(['Date','Market Cap'],inplace=True,axis=1)
crypto

Open    High     Low   Close       Volume
0    161.62  166.40  161.29  165.09  328095197.0
1    166.44  166.69  159.65  161.65  396994620.0
2    170.34  170.96  164.39  166.41  397472839.0
3    173.35  173.47  161.74  170.32  532350698.0
4    179.71  181.30  170.21  173.37  569515279.0
..      ...     ...     ...     ...          ...
760  109.90  208.40  109.30  208.40   20708000.0
761  116.46  123.56  104.45  112.06   10779600.0
762   87.70  125.11   83.15  113.47    8902820.0
763   70.27   98.51   61.19   87.06    4748070.0
764   88.30   89.57   50.68   68.75    2585660.0

[765 rows x 5 columns]

In [4]:
crypto.describe()

Open        High         Low       Close        Volume
count  765.000000  765.000000  765.000000  765.000000  7.650000e+02
mean   146.886915  153.053908  140.884497  146.978575  8.729238e+08
std     64.046351   67.069378   60.851436   64.030580  9.081246e+08
min     42.500000   51.550000   36.870000   42.750000  2.585660e+06
25%     89.570000   94.100000   86.110000   89.600000  2.245673e+08
50%    151.850000  158.010000  146.480000  152.160000  5.204244e+08
75%    188.980000  194.120000  182.040000  188.980000  1.192456e+09
max    420.680000  441.200000  363.010000  422.740000  7.460265e+09

In [5]:
crypto.isna().sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [6]:
crypto['target']=crypto['Close'].shift(-1)
crypto

Open    High     Low   Close       Volume  target
0    161.62  166.40  161.29  165.09  328095197.0  161.65
1    166.44  166.69  159.65  161.65  396994620.0  166.41
2    170.34  170.96  164.39  166.41  397472839.0  170.32
3    173.35  173.47  161.74  170.32  532350698.0  173.37
4    179.71  181.30  170.21  173.37  569515279.0  179.70
..      ...     ...     ...     ...          ...     ...
760  109.90  208.40  109.30  208.40   20708000.0  112.06
761  116.46  123.56  104.45  112.06   10779600.0  113.47
762   87.70  125.11   83.15  113.47    8902820.0   87.06
763   70.27   98.51   61.19   87.06    4748070.0   68.75
764   88.30   89.57   50.68   68.75    2585660.0     NaN

[765 rows x 6 columns]

In [7]:
crypto.dropna(inplace=True)
crypto


Open    High     Low   Close       Volume  target
0    161.62  166.40  161.29  165.09  328095197.0  161.65
1    166.44  166.69  159.65  161.65  396994620.0  166.41
2    170.34  170.96  164.39  166.41  397472839.0  170.32
3    173.35  173.47  161.74  170.32  532350698.0  173.37
4    179.71  181.30  170.21  173.37  569515279.0  179.70
..      ...     ...     ...     ...          ...     ...
759  205.76  243.79  155.38  174.81   36795500.0  208.40
760  109.90  208.40  109.30  208.40   20708000.0  112.06
761  116.46  123.56  104.45  112.06   10779600.0  113.47
762   87.70  125.11   83.15  113.47    8902820.0   87.06
763   70.27   98.51   61.19   87.06    4748070.0   68.75

[764 rows x 6 columns]

In [8]:
#splitting features and target
x=crypto.iloc[:,:-1]
y=crypto.iloc[:,-1]
print(x)
print(y)

       Open    High     Low   Close       Volume
0    161.62  166.40  161.29  165.09  328095197.0
1    166.44  166.69  159.65  161.65  396994620.0
2    170.34  170.96  164.39  166.41  397472839.0
3    173.35  173.47  161.74  170.32  532350698.0
4    179.71  181.30  170.21  173.37  569515279.0
..      ...     ...     ...     ...          ...
759  205.76  243.79  155.38  174.81   36795500.0
760  109.90  208.40  109.30  208.40   20708000.0
761  116.46  123.56  104.45  112.06   10779600.0
762   87.70  125.11   83.15  113.47    8902820.0
763   70.27   98.51   61.19   87.06    4748070.0

[764 rows x 5 columns]
0      161.65
1      166.41
2      170.32
3      173.37
4      179.70
        ...  
759    208.40
760    112.06
761    113.47
762     87.06
763     68.75
Name: target, Length: 764, dtype: float64


In [9]:
train=crypto.iloc[:-157]
test=crypto.iloc[-157:]
print(train)
print(test)

       Open    High     Low   Close       Volume  target
0    161.62  166.40  161.29  165.09  328095197.0  161.65
1    166.44  166.69  159.65  161.65  396994620.0  166.41
2    170.34  170.96  164.39  166.41  397472839.0  170.32
3    173.35  173.47  161.74  170.32  532350698.0  173.37
4    179.71  181.30  170.21  173.37  569515279.0  179.70
..      ...     ...     ...     ...          ...     ...
602   59.40   59.60   58.39   58.75   97374625.0   59.40
603   59.50   60.91   57.96   59.40  118232833.0   59.49
604   55.33   62.59   54.83   59.49  175668105.0   55.34
605   57.34   57.34   54.80   55.34  119936671.0   57.47
606   59.30   61.42   54.24   57.47  191336609.0   59.29

[607 rows x 6 columns]
       Open    High     Low   Close       Volume  target
607   71.05   74.30   59.03   59.29  237454559.0   71.05
608   69.96   71.06   69.24   71.05   83823672.0   69.96
609   71.42   72.02   69.50   69.96   96837329.0   71.45
610   71.77   74.37   69.11   71.45  143465843.0   71.75
611   8

In [10]:
scaler_x=StandardScaler()


x_train=train.drop(columns=['target'])
x_test=test.drop(columns=['target'])
x_train_scaled=scaler_x.fit_transform(x_train)
x_test_scaled=scaler_x.transform(x_test)

y_train=train['target']
y_test=test['target']


print(x_train_scaled)
print(x_test_scaled)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[-4.89976941e-02 -7.21222029e-02  5.48256464e-02  6.39631075e-03
  -8.06583236e-01]
 [ 3.18806923e-02 -6.75065183e-02  2.55961852e-02 -5.14644897e-02
  -7.31715479e-01]
 [ 9.73217103e-02  4.55458968e-04  1.10076457e-01  2.85987109e-02
  -7.31195835e-01]
 ...
 [-1.83251713e+00 -1.72437814e+00 -1.84259413e+00 -1.76979570e+00
  -9.72214151e-01]
 [-1.79878984e+00 -1.80793795e+00 -1.84312882e+00 -1.83959870e+00
  -1.03277326e+00]
 [-1.76590153e+00 -1.74300004e+00 -1.85310961e+00 -1.80377210e+00
  -9.55188381e-01]]
[[-1.56873949 -1.53799998 -1.76773819 -1.7731597  -0.90507552]
 [-1.58702941 -1.58956832 -1.58576698 -1.5753565  -1.0720145 ]
 [-1.56253098 -1.57428881 -1.58113304 -1.5936903  -1.05787355]
 [-1.55665807 -1.53688585 -1.58808395 -1.5686285  -1.0072059 ]
 [-1.41738616 -1.38170335 -1.58737103 -1.5635825  -0.94585635]
 [-1.44104561 -1.41449063 -1.41894517 -1.4236401  -1.02885748]
 [-1.36553674 -1.39682369 -1.43926321 -1.4475245  -1.01690913]
 [-1.31217714 -1.32201777 -1.37028881 -1.37

In [11]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train_scaled,y_train)
y_pred=model.predict(x_test_scaled)

print(y_pred)

print(y_test)

[ 71.08401055  69.94381721  71.40697908  71.7628554   80.09913605
  78.63552     83.16336638  86.33937934  84.63222463  84.31219302
  82.87706116  82.4795848   78.61404845  66.09524692  64.95198529
  65.00295036  64.22768019  64.66272039  65.9987371   64.48316548
  64.37715653  66.02188799  67.32573527  66.58073311  65.84085073
  66.8703525   67.15574953  67.23533864  68.53910457  68.96791041
  67.66000328  66.19354257  64.96986601  65.90563816  65.2365718
  66.79725239  66.85266347  65.61005467  66.88380784  66.95291085
  67.15374422  63.40393026  65.32129243  66.89688015  66.84180855
  67.23140947  67.80474653  74.48638279  68.30566504  61.21718062
  69.13884327  65.82693446  65.30311654  67.50140666  67.05860939
  67.67949898  63.43525139  62.28403132  62.3313126   62.69330388
  64.52795467  65.58431475  64.9134233   66.74715635  66.00458234
  67.39914797  62.47149982  62.49689023  61.26412744  62.85126446
  63.85427884  65.63944477  64.21155511  64.04387269  66.28567283
  63.504650

In [12]:
residual=y_test-y_pred.reshape(-1)
print(residual)

607   -0.034011
608    0.016183
609    0.043021
610   -0.012855
611   -0.029136
         ...   
759    2.465852
760    2.087616
761   -3.016671
762   -0.658374
763   -1.565192
Name: target, Length: 157, dtype: float64


In [13]:
from sklearn.metrics import mean_absolute_error,r2_score
per_error=((mean_absolute_error(y_test,y_pred))/crypto['target'].mean())*100
r2=r2_score(y_test,y_pred)
print(per_error)
print(r2)
print(crypto['target'].mean())

0.1930573256279839
0.999157923765139
146.95486910994762


In [14]:
scaler_x_full=StandardScaler()


x_scaled=scaler_x_full.fit_transform(x)

print(y)
model=LinearRegression()
model.fit(x_scaled,y)
prediction=model.predict(x_scaled)

print(prediction)

0      161.65
1      166.41
2      170.32
3      173.37
4      179.70
        ...  
759    208.40
760    112.06
761    113.47
762     87.06
763     68.75
Name: target, Length: 764, dtype: float64
[161.59392819 166.41769575 170.31686097 173.3203514  179.69973512
 178.55259476 181.95712565 177.56224251 170.90795905 171.05665565
 169.35021682 182.60260822 168.18502937 166.7234106  161.81406521
 165.52089679 191.85863851 208.94184725 196.89201501 177.86628815
 193.6946313  166.02425476 161.56953806 162.1329976  166.84623283
 159.83900637 154.40969655 157.7139726  161.12305598 158.13915617
 159.09296436 157.16901202 160.10845301 166.86365267 162.18375881
 167.64430206 159.73084937 152.1581007  153.74485301 158.64556462
 164.63059149 164.83836048 163.48695501 166.7695683  169.83447149
 174.87548169 173.78856293 180.93209467 175.48837383 166.23679321
 168.84436797 164.65238874 157.89637431 159.93104474 160.48535824
 159.43350836 160.72549246 169.5631212  168.51624987 170.81624977
 169.8052869

In [16]:
joblib.dump(model,'crypto.pkl')
joblib.dump(scaler_x,'scaler_x.pkl')
joblib.dump(scaler_x_full,'scaler_x_full.pkl')

scalar_x_full=joblib.load('scaler_x_full.pkl')
scaler_x=joblib.load('scaler_x.pkl')
model=joblib.load('crypto.pkl')


In [17]:
print(scaler_x.mean_.shape)  # Will show (1,) or (5,)

(5,)
